model:
  channels: 32
  hidden_dim: 32
  depth: 0
  activation: ReLU
data:
  size: 32
  length: 512
  batch_size: 2
optimizer:
 class_path: torch.optim.adam.Adam
 init_args:
   lr: 0.0005
lr_scheduler:
 class_path: torch.optim.lr_scheduler.ExponentialLR
 init_args:
   gamma: 0.1
trainer:
 max_epochs: 3
 enable_checkpointing: False
 accelerator: "gpu"
 gpus: 1
#  logger:
#  - class_path: pytorch_lightning.loggers.CSVLogger
#    init_args:
#      save_dir: logs
#      name: csv-logger
 logger:
 - class_path: loggers.SigOptLogger
   init_args:
     save_dir: logs
     name: egnnfull101
     config_path: ./loggers/sigopt_params.yaml
seed_everything: 42