model:
  channels: 32
  hidden_dim: 32
  depth: 0
  activation: ReLU
data:
  size: 32
  length: 512
  batch_size: 2
optimizer:
 class_path: torch.optim.adam.Adam
 init_args:
   lr: 0.0005
lr_scheduler:
 class_path: torch.optim.lr_scheduler.ExponentialLR
 init_args:
   gamma: 0.1
trainer:
 max_epochs: 10
 enable_checkpointing: False
 accelerator: "gpu"
 strategy: ddp
 gpus: 2

seed_everything: 42